bdp/views/manager.py
# encoding: utf-8

from datetime import datetime
from bson.objectid import ObjectId
from functools import wraps

from flask import Blueprint
from flask import render_template
from flask import abort
from flask import request
from flask import Response
from flask import flash
from flask import redirect
from flask import url_for
from flask import json
from flask import jsonify
from flask import current_app as app
from flask.ext.paginate import Pagination

from flask.ext import login as flask_login
from flask.ext.login import login_required, current_user


from bdp import mongo, login_manager

def to_int(num, default=0):
	""" 转化为整形 """
	try:
		return int(num)
	except Exception, e:
		return default

class User(flask_login.UserMixin):
	pass

@login_manager.user_loader
def user_loader(username):
	manager = mongo.db.managers.find_one({'username': username})

	if not manager:
		return

	user = User()
	user.id = username
	user.role = manager.get('role')
	return user

@login_manager.request_loader
def request_loader(request):
	username = request.form.get('username')
	manager = mongo.db.managers.find_one({'username': username})
	if not manager:
		return

	user = User()
	user.id = username
	user.role = manager.get('role')
	return user


page = Blueprint('manager', __name__, template_folder='templates')

@page.route('/login', methods=['GET', 'POST'])
def login():
	if request.method == 'GET':
		return render_template('login.html')

	# 从数据库里获取用户信息
	username = request.form['username']
	manager = mongo.db.managers.find_one({'username': username})

	if manager and manager.get('enable') == False:
		flash('账户不可用')
		return render_template('login.html')

	# 验证密码是否正确
	if manager and request.form['password'] == manager.get('password'):
		user = User()
		user.id = username
		user.role = manager.get('role')

		flask_login.login_user(user)

		return redirect(url_for('user.index'))

	flash('用户名或密码错误！')
	return render_template('login.html')

@page.route('/logout')
def logout():
	flask_login.logout_user()
	return redirect(url_for('manager.login'))

@page.route('/managers')
@login_required
def index():
	limit = 100
	page = int(request.args.get('page', 1))
	if current_user.role == 'root':
		q = {}
	else:
		q = {'created_by': current_user.id}
	managers = mongo.db.managers.find(q)
	total = mongo.db.managers.count(q)
	pagination = Pagination(page=page, total=total, record_name='')
	return render_template('managers/index.html', managers=managers, pagination=pagination)

@page.route('/manager/new', methods=['GET'])
@login_required
def new():
	manager = {}
	if current_user.role == 'agent':
		current_mananger = mongo.db.managers.find_one({'username': current_user.id})
		hint = '已使用语音授权：%s/%s，已使用siri授权：%s/%s，已使用匿名授权：%s/%s' % \
		(current_mananger['used_voice_licenses'], current_mananger['voice_licenses'],
			current_mananger['used_siri_licenses'], current_mananger['siri_licenses'],
			current_mananger.get('used_anonymous_licenses', 0), current_mananger.get('anonymous_licenses',0),)
		manager['hint'] = hint

	return render_template('managers/new.html', manager=manager)

@page.route('/managers', methods=['POST'])
@login_required
def create():
	form = request.form
	username = form['username'].strip()
	password = form['password'].strip()
	backup = form['backup']
	enable = form['enable']
	role = form.get('role', 'sub-agent')
	voice_licenses = to_int(form['voice_licenses'])
	siri_licenses = to_int(form['siri_licenses'])
	anonymous_licenses = to_int(form['anonymous_licenses'])
	licenses = voice_licenses + siri_licenses + anonymous_licenses
	created_at = datetime.now()
	
	if current_user.role == 'agent':
		# 获取当前管理员数据
		manager = mongo.db.managers.find_one({'username': current_user.id})
		manager_voice_licenses = manager.get('voice_licenses')
		manager_siri_licenses = manager.get('siri_licenses')
		manager_anonymous_licenses = manager.get('anonymous_licenses')
		manager_used_voice_licenses = manager.get('used_voice_licenses')
		manager_used_siri_licenses = manager.get('used_siri_licenses')
		manager_used_anonymous_licenses = manager.get('used_anonymous_licenses')

		if voice_licenses + manager_used_voice_licenses > manager_voice_licenses:
			flash('语音授权超出可用值！')
			return redirect(url_for('manager.index'))
		if siri_licenses + manager_used_siri_licenses > manager_siri_licenses:
			flash('siri授权超出可用值！')
			return redirect(url_for('manager.index'))
		if anonymous_licenses + manager_used_anonymous_licenses > manager_anonymous_licenses:
			flash('匿名授权超出可用值！')
			return redirect(url_for('manager.index'))
		# 增量
		inc = {
			'used_licenses': voice_licenses + siri_licenses + anonymous_licenses, 
			'used_voice_licenses': voice_licenses, 
			'used_siri_licenses': siri_licenses,
			'used_anonymous_licenses': anonymous_licenses,
		}
		mongo.db.managers.update({'username': current_user.id}, {'$inc': inc})


	data = {
		'username': username,
		'password': password,
		'backup': backup,
		'licenses': licenses,
		'voice_licenses': voice_licenses,
		'siri_licenses': siri_licenses,
		'anonymous_licenses': anonymous_licenses,
		'enable': enable == 'true' and True or False,
		'used_licenses': 0,
		'used_voice_licenses': 0,
		'used_siri_licenses': 0,
		'used_anonymous_licenses': 0,
		'role': role,
		'created_at': created_at,
		'created_by': current_user.id,
	}

	manager_id = mongo.db.managers.insert_one(data).inserted_id

	return redirect(url_for('manager.index'))

@page.route('/manager/update/<manager_id>', methods=['POST'])
@login_required
def update(manager_id):
	form = request.form 
	username = form['username'].strip()
	password = form['password'].strip()
	backup = form['backup']
	enable = form['enable']
	role = form.get('role', 'sub-agent')
	voice_licenses = to_int(form['voice_licenses'])
	siri_licenses = to_int(form['siri_licenses'])
	anonymous_licenses = to_int(form['anonymous_licenses'])
	licenses = voice_licenses + siri_licenses + anonymous_licenses

	if current_user.role == 'agent':
		# 获取当前管理员数据
		manager = mongo.db.managers.find_one({'username': current_user.id})
		manager_voice_licenses = manager.get('voice_licenses')
		manager_siri_licenses = manager.get('siri_licenses')
		manager_anonymous_licenses = manager.get('anonymous_licenses')
		manager_used_voice_licenses = manager.get('used_voice_licenses')
		manager_used_siri_licenses = manager.get('used_siri_licenses')
		manager_used_anonymous_licenses = manager.get('used_anonymous_licenses')

		if voice_licenses + manager_used_voice_licenses > manager_voice_licenses:
			flash('语音授权超出可用值！')
			return redirect(url_for('manager.index'))
		if siri_licenses + manager_used_siri_licenses > manager_siri_licenses:
			flash('siri授权超出可用值！')
			return redirect(url_for('manager.index'))
		if anonymous_licenses + manager_used_anonymous_licenses > manager_anonymous_licenses:
			flash('匿名授权超出可用值！')
			return redirect(url_for('manager.index'))
		# 增量
		inc = {
			'used_licenses': voice_licenses + siri_licenses + anonymous_licenses, 
			'used_voice_licenses': voice_licenses, 
			'used_siri_licenses': siri_licenses,
			'used_anonymous_licenses': anonymous_licenses,
		}
		mongo.db.managers.update({'username': current_user.id}, {'$inc': inc})

	manager = {
		'username': username,
		'password': password,
		'backup': backup,
		'role': role,
		'anonymous_licenses': anonymous_licenses,
		'voice_licenses': voice_licenses,
		'siri_licenses': siri_licenses,
		'licenses': licenses,
		'enable': enable == 'true' and True or False,
	}

	result = mongo.db.managers.update_one({'_id': ObjectId(manager_id)}, {'$set': manager})

	return redirect(url_for('manager.index'))

@page.route('/manager/edit/<manager_id>', methods=['GET'])
@login_required
def edit(manager_id):
	manager = mongo.db.managers.find_one({'_id': ObjectId(manager_id)})
	return render_template('managers/edit.html', manager=manager)

@page.route('/manager/show/<manager_id>', methods=['GET'])
@login_required
def show(manager_id):
	manager = mongo.db.managers.find_one({'_id': ObjectId(manager_id)})
	users = mongo.db.users.find({'created_by': manager.get('username')})
	return render_template('managers/show.html', manager=manager, users=users)

@page.route('/manager/disable/<manager_id>', methods=['GET'])
def disable(manager_id):
	result = mongo.db.managers.update_one({'_id': ObjectId(manager_id)}, {'$set': {'enable': False}})
	return redirect(url_for('manager.index'))

@page.route('/manager/delete/<manager_id>', methods=['GET'])
def delete(manager_id):
	mongo.db.managers.remove({'_id': ObjectId(manager_id)})
	return redirect(url_for('manager.index'))

bdp/views/user.py
# encoding: utf-8

from datetime import datetime
from bson.objectid import ObjectId
from functools import wraps

from flask import Blueprint
from flask import render_template
from flask import abort
from flask import request
from flask import Response
from flask import flash
from flask import redirect
from flask import url_for
from flask import json
from flask import jsonify
from flask import current_app as app
from flask_paginate import Pagination

from flask.ext.login import current_user
from flask.ext.login import login_required

from pymongo.errors import DuplicateKeyError

from bdp import mongo

def to_int(num, default=1):
	""" 转化为整形 """
	try:
		return int(num)
	except Exception, e:
		return default

def check_auth(username, password):
	""" 校验用户名和密码是否正确 """
	return username == 'admin' and password == 'secret'

def authenticate():
	""" Sends a 401 response that enables basic auth """
	return Response(
	'Could not verify your access level for that URL.\n'
	'You have to login with proper credentials', 401,
	{'WWW-Authenticate': 'Basic realm="Login Required"'})

def requires_auth(f):
	@wraps(f)
	def decorated(*args, **kwargs):
		auth = request.authorization
		if not auth or not check_auth(auth.username, auth.password):
			return authenticate()
		return f(*args, **kwargs)
	return decorated

page = Blueprint('user', __name__, template_folder='templates')

@page.route('/')
@login_required
def index():
	limit = 100
	page = to_int(request.args.get('page'))
	_type = request.args.get('_type')

	if current_user.role != 'root':
		created_by = current_user.id
		q = {'created_by': created_by}
		current_mananger = mongo.db.managers.find_one({'username': current_user.id})
		hint = '已使用语音授权：%s/%s，已使用siri授权：%s/%s，已使用匿名授权：%s/%s' % \
		(current_mananger['used_voice_licenses'], current_mananger['voice_licenses'],
			current_mananger['used_siri_licenses'], current_mananger['siri_licenses'],
			current_mananger.get('used_anonymous_licenses', 0), current_mananger.get('anonymous_licenses',0),)
	else:
		q = {}
		hint = ''
		created_by = None

	if _type:
		q['type'] = _type

	users = mongo.db.users.find(q).sort([('created_at', -1)]).skip(limit*(page-1)).limit(limit)
	total = mongo.db.users.count(q)
	pagination = Pagination(page=page, per_page=limit, total=total, record_name='users')
	return render_template('users/index.html', users=users, pagination=pagination, _type=_type, hint=hint)

@page.route('/user/new', methods=['GET'])
@login_required
def new():
	user = {}
	return render_template('users/new.html', user=user)

@page.route('/api/users', methods=['POST'])
def multiple_create():
	try:
		data = request.get_json()
		users = data.get('users')
		formatted_users = []
		for user in users:
			if user.get('type', '') == 'siri':
				user['udid'] += '-W'
			elif user.get('type', '') == 'anonymous':
				user['udid'] += '-V'
			user['status'] = True
			user['created_at'] = datetime.now()
			user['created_by'] = None
			formatted_users.append(user)
		mongo.db.users.insert(formatted_users)
		return jsonify({'code': 200})
	except Exception, e:
		return jsonify({'code': 500})

	

@page.route('/users', methods=['POST'])
@login_required
def create():
	try:
		form = request.form
		username = form['username'].strip()
		backup = form['backup']
		status = form['status']
		_type = form['type']
		udid = form['udid'].strip()
		created_at = datetime.now()

		if current_user.role != 'root':
			created_by = current_user.id
		else:
			created_by = None

		manager = mongo.db.managers.find_one({'username': current_user.id})

		if manager.get('enable') == False:
			# 管理被禁用
			flash('无操作权限')
			return redirect(url_for('user.index'))

		inc = {'used_licenses': 1}

		if _type == 'siri':
			udid = '%s-W' % udid
			if manager.get('role') != 'root':
				siri_licenses = manager.get('siri_licenses')
				used_siri_licenses = manager.get('used_siri_licenses')
				if siri_licenses <= used_siri_licenses:
					flash('siri授权数不足')
					return redirect(url_for('user.index'))
				inc['used_siri_licenses'] = 1
		elif _type == 'anonymous':
			udid = '%s-V' % udid
			if manager.get('role') != 'root':
				anonymous_licenses = manager.get('anonymous_licenses')
				used_anonymous_licenses = manager.get('used_anonymous_licenses')
				if anonymous_licenses <= used_anonymous_licenses:
					flash('匿名授权数不足')
					return redirect(url_for('user.index'))
				inc['used_anonymous_licenses'] = 1
		else:
			if manager.get('role') != 'root':
				voice_licenses = manager.get('voice_licenses')
				used_voice_licenses = manager.get('used_voice_licenses')
				if voice_licenses <= used_voice_licenses:
					flash('语音授权数不足')
					return redirect(url_for('user.index'))
				inc['used_voice_licenses'] = 1


		user = {
			'type': _type,
			'username': username,
			'backup': backup,
			'udid': udid,
			'status': status == 'true' and True or False,
			'created_at': created_at,
			'created_by': created_by,
		}

		user_id = mongo.db.users.insert_one(user).inserted_id

		mongo.db.managers.update({'username': current_user.id}, {'$inc': inc})
		return redirect(url_for('user.index'))
	except DuplicateKeyError:
		flash('udid重复')
		return redirect(url_for('user.index'))
	except Exception, e:
		flash(e)
		return redirect(url_for('user.index'))
		
@page.route('/user/update/<user_id>', methods=['POST'])
@login_required
def update(user_id):
	try:
		form = request.form 
		_type = form['type']
		username = form['username'].strip()
		backup = form['backup']
		status = form['status']
		udid = form['udid'].strip()

		if _type == 'siri':
			udid = '%s-W' % udid
		elif _type == 'anonymous':
			udid = '%s-V' % udid

		user = {
			'type': _type,
			'username': username,
			'udid': udid,
			'status': status == 'true' and True or False,
			'backup': backup,
		}

		result = mongo.db.users.update_one({'_id': ObjectId(user_id)}, {'$set': user})
	except DuplicateKeyError:
		flash('udid重复')
	except Exception, e:
		flash(e)
	finally:
		return redirect(url_for('user.index'))

@page.route('/user/edit/<user_id>', methods=['GET'])
@login_required
def edit(user_id):
	user = mongo.db.users.find_one({'_id': ObjectId(user_id)})
	return render_template('users/edit.html', user=user)

@page.route('/user/delete/<user_id>', methods=['GET'])
@login_required
def delete(user_id):
	mongo.db.users.remove({'_id': ObjectId(user_id)})
	return redirect(url_for('user.index'))

@page.route('/user/statistics', methods=['GET'])
def statistics():
	"""统计"""
	total = mongo.db.users.count()

	condition = [
     	{ '$project': {'day': {'$dateToString': { 'format': "%Y-%m-%d", 'date': "$created_at" }}}},
     	{ '$group': {'_id': "$day", 'number': {'$sum': 1 }}},
     	{ '$sort': {'_id': -1}},
   	]

	result = mongo.db.users.aggregate(condition)

	return render_template('users/statistics.html', total=total, result=result) 

	

bdp/templates/managers/_form.html
{% extends "layout.html" %}
{% block body %}
	<h4 class="page-header">{{ page_header }}</h4>
	<div class="col-md-6">
		{% if manager.get('hint') %}
			<div class="alert alert-success" role="alert">
  				<a href="#" class="alert-link">{{ manager.get('hint') }}</a>
			</div>
		{% endif %}

		{% if manager._id %}
		<form action="{{ url_for('manager.update', manager_id=manager._id) }}" method="POST">
		{% else %}
		<form action="{{ url_for('manager.create') }}" method="POST">
		{% endif %}
			{% if current_user.role == 'root' %}
			<div class="form-group">
				<label class="radio-inline">
				  	<input type="radio" name="role" value="agent" {% if manager.get('role', 'agent') == 'agent' %} checked {% endif %}> 一级代理
				</label>
				<label class="radio-inline">
				  	<input type="radio" name="role" value="sub-agent" {% if manager.get('role', 'agent') == 'sub-agent' %} checked {% endif %}> 二级代理
				</label>
			</div>
			{% endif %}

			<div class="form-group">
				<label for="">用户名</label>
				<input type="text" class="form-control" name="username" placeholder="" value="{{ manager.get('username', '') }}" required>
			</div>

			<div class="form-group">
				<label for="">密码</label>
				<input type="text" class="form-control" name="password" placeholder="" value="{{ manager.get('password', '') }}" required>
			</div>
			
			<div class="form-group">
				<label for="">语音授权数</label>
				<input type="text" class="form-control" name="voice_licenses" placeholder="" value="{{ manager.get('voice_licenses', '') }}">
			</div>

			<div class="form-group">
				<label for="">siri授权数</label>
				<input type="text" class="form-control" name="siri_licenses" placeholder="" value="{{ manager.get('siri_licenses', '') }}">
			</div>

			<div class="form-group">
				<label for="">匿名授权数</label>
				<input type="text" class="form-control" name="anonymous_licenses" placeholder="" value="{{ manager.get('anonymous_licenses', '') }}">
			</div>

			<div class="form-group">
                <label for="">状态</label>
                <select name="enable" class="form-control">
                    <option value="true">可用</option>
                    <option value="false" {% if manager.get('enable') == False %} selected {% endif %}>不可用</option>
    			</select>
            </div>

			<div class="form-group">
				<label for="">备注</label>
				<input type="text" class="form-control" name="backup" placeholder="" value="{{ manager.get('backup', '') }}">
			</div>

			<button class="btn btn-primary" type="submit">提交</button>
		</form>
	</div>
{% endblock %}

bdp/templates/managers/edit.html
{% set page_header = '修改代理' %}

{% include 'managers/_form.html' %}

bdp/templates/managers/index.html
{% extends "layout.html" %}
{% block body %}
	<h4 class="page-header">代理列表</h4>
	<a href="{{ url_for('manager.new') }}" class="btn btn-primary btn-sm pull-right" style="margin-bottom: 5px;">创建代理</a>
	<table class="table table-bordered">
		<thead>
			<tr>
				<th></th>
				<th>角色</th>
				<th>用户名</th>
				<th>密码</th>
				<th>授权数</th>
				<th>已用</th>
				<th>可用</th>
				<th>语音</th>
				<th>siri</th>
				<th>匿名</th>
				<th>状态</th>
				<th>备注</th>
				<th>创建人</th>
				<th>操作</th>
			</tr>
		</thead>
		<tbody>
			{% for manager in managers %}
				{% if manager.get('role') != 'root' %}
				<tr>
					<td>{{ loop.index }}</td>
					<td>{{ manager.get('role')}}</td>
					<td>{{ manager.get('username') }}</td>
					<td>{{ manager.get('password') }}</td>
					<td>{{ manager.get('licenses', 0) | int }}</td>
					<td>{{ manager.get('used_licenses', 0) | int }}</td>
					{% if manager.get('licenses', -1) < manager.get('used_licenses', 0) %}
						<td>0</td>
					{% else %}
						<td>{{ (manager.get('licenses') - manager.get('used_licenses')) | int }}</td>
					{% endif %}
					<td>{{ manager.get('voice_licenses', 0) }}</td>
					<td>{{ manager.get('siri_licenses', 0) }}</td>
					<td>{{ manager.get('anonymous_licenses', 0) }}</td>
					<td>{{ manager.enable == False and '不可用' or '可用' }}</td>
					<td>{{ manager.get('backup', '') }}</td>
					<td>{{ manager.get('created_by', '') }}</td>
					
					<td>
						<!-- <a class="btn btn-primary btn-xs"></a> -->
						<a class="btn btn-primary btn-xs" href="{{ url_for('manager.edit', manager_id=manager._id) }}">编辑</a>
						<a class="btn btn-info btn-xs" target="_blank" href="{{ url_for('manager.show', manager_id=manager._id) }}">查看</a>
						<a class="btn btn-warning btn-xs" target="_blank" href="{{ url_for('manager.disable', manager_id=manager._id) }}">禁用</a>
						<a class="btn btn-danger btn-xs" target="_blank" href="{{ url_for('manager.delete', manager_id=manager._id) }}">删除</a>
					</td>
				</tr>
				{% endif %}
			{% endfor %}
		</tbody>
	</table>
{% endblock %}

bdp/templates/managers/new.html
{% set page_header = '创建代理' %}

{% include 'managers/_form.html' %}

bdp/templates/managers/show.html
{% extends "layout.html" %}
{% block body %}
	<h4 class="page-header">用户列表【{{manager.get('username')}}】</h4>
	<!-- <a href="{{ url_for('user.new') }}" class="btn btn-primary btn-sm pull-right" style="margin-bottom: 5px;">创建用户</a> -->
	<table class="table table-bordered">
		<thead>
			<tr>
				<th></th>
				<th>UDID</th>
				<th>用户名</th>
				<th>类型</th>
				<th>状态</th>
				<th>创建时间</th>
				<th>操作</th>
			</tr>
		</thead>
		<tbody>
			{% for user in users %}
				<tr>
					<td>{{ loop.index }}</td>
					<td>{{ user.get('udid') }}</td>
					<td>{{ user.get('username') }}</td>
					<td>{% if user.get('type') == 'voice' %} 语音 {% elif user.get('type') == 'siri' %} siri {% else %} 匿名 {% endif %}</td>
					<td>
						{% if user.get('status') %}
						可用
						{% else %}
						不可用
						{% endif %}
					</td>
					<td>{{ user.created_at.strftime("%Y-%m-%d %H:%M:%S") }}</td>
					<td>
						<!-- <a class="btn btn-primary btn-xs"></a> -->
						<a class="btn btn-primary btn-xs" href="{{ url_for('user.edit', user_id=user._id) }}">编辑</a>
						
					</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% endblock %}