bdp/views/manager.py
# encoding: utf-8

from datetime import datetime
from bson.objectid import ObjectId
from functools import wraps

from flask import Blueprint
from flask import render_template
from flask import abort
from flask import request
from flask import Response
from flask import flash
from flask import redirect
from flask import url_for
from flask import json
from flask import jsonify
from flask import current_app as app
from flask.ext.paginate import Pagination

from flask.ext import login as flask_login
from flask.ext.login import login_required, current_user


from bdp import mongo, login_manager

def to_int(num, default=0):
	""" 转化为整形 """
	try:
		return int(num)
	except Exception, e:
		return default

class User(flask_login.UserMixin):
	pass

@login_manager.user_loader
def user_loader(username):
	manager = mongo.db.managers.find_one({'username': username})

	if not manager:
		return

	user = User()
	user.id = username
	user.role = manager.get('role')
	return user

@login_manager.request_loader
def request_loader(request):
	username = request.form.get('username')
	manager = mongo.db.managers.find_one({'username': username})
	if not manager:
		return

	user = User()
	user.id = username
	user.role = manager.get('role')
	return user


page = Blueprint('manager', __name__, template_folder='templates')

@page.route('/login', methods=['GET', 'POST'])
def login():
	if request.method == 'GET':
		return render_template('login.html')

	# 从数据库里获取用户信息
	username = request.form['username']
	manager = mongo.db.managers.find_one({'username': username})

	if manager and manager.get('enable') == False:
		flash('账户不可用')
		return render_template('login.html')

	# 验证密码是否正确
	if manager and request.form['password'] == manager.get('password'):
		user = User()
		user.id = username
		user.role = manager.get('role')

		flask_login.login_user(user)

		return redirect(url_for('user.index'))

	flash('用户名或密码错误！')
	return render_template('login.html')

@page.route('/logout')
def logout():
	flask_login.logout_user()
	return redirect(url_for('manager.login'))

@page.route('/managers')
@login_required
def index():
	limit = 100
	page = int(request.args.get('page', 1))
	if current_user.role == 'root':
		q = {}
	else:
		q = {'created_by': current_user.id}
	managers = mongo.db.managers.find(q)
	total = mongo.db.managers.count(q)
	pagination = Pagination(page=page, total=total, record_name='')
	return render_template('managers/index.html', managers=managers, pagination=pagination)

@page.route('/manager/new', methods=['GET'])
@login_required
def new():
	manager = {}
	if current_user.role == 'agent':
		current_mananger = mongo.db.managers.find_one({'username': current_user.id})
		hint = '已使用语音授权：%s/%s，已使用siri授权：%s/%s，已使用匿名授权：%s/%s' % \
		(current_mananger['used_voice_licenses'], current_mananger['voice_licenses'],
			current_mananger['used_siri_licenses'], current_mananger['siri_licenses'],
			current_mananger.get('used_anonymous_licenses', 0), current_mananger.get('anonymous_licenses',0),)
		manager['hint'] = hint

	return render_template('managers/new.html', manager=manager)

@page.route('/managers', methods=['POST'])
@login_required
def create():
	form = request.form
	username = form['username'].strip()
	password = form['password'].strip()
	backup = form['backup']
	enable = form['enable']
	role = form.get('role', 'sub-agent')
	voice_licenses = to_int(form['voice_licenses'])
	siri_licenses = to_int(form['siri_licenses'])
	anonymous_licenses = to_int(form['anonymous_licenses'])
	licenses = voice_licenses + siri_licenses + anonymous_licenses
	created_at = datetime.now()
	
	if current_user.role == 'agent':
		# 获取当前管理员数据
		manager = mongo.db.managers.find_one({'username': current_user.id})
		manager_voice_licenses = manager.get('voice_licenses')
		manager_siri_licenses = manager.get('siri_licenses')
		manager_anonymous_licenses = manager.get('anonymous_licenses')
		manager_used_voice_licenses = manager.get('used_voice_licenses')
		manager_used_siri_licenses = manager.get('used_siri_licenses')
		manager_used_anonymous_licenses = manager.get('used_anonymous_licenses')

		if voice_licenses + manager_used_voice_licenses > manager_voice_licenses:
			flash('语音授权超出可用值！')
			return redirect(url_for('manager.index'))
		if siri_licenses + manager_used_siri_licenses > manager_siri_licenses:
			flash('siri授权超出可用值！')
			return redirect(url_for('manager.index'))
		if anonymous_licenses + manager_used_anonymous_licenses > manager_anonymous_licenses:
			flash('匿名授权超出可用值！')
			return redirect(url_for('manager.index'))
		# 增量
		inc = {
			'used_licenses': voice_licenses + siri_licenses + anonymous_licenses, 
			'used_voice_licenses': voice_licenses, 
			'used_siri_licenses': siri_licenses,
			'used_anonymous_licenses': anonymous_licenses,
		}
		mongo.db.managers.update({'username': current_user.id}, {'$inc': inc})


	data = {
		'username': username,
		'password': password,
		'backup': backup,
		'licenses': licenses,
		'voice_licenses': voice_licenses,
		'siri_licenses': siri_licenses,
		'anonymous_licenses': anonymous_licenses,
		'enable': enable == 'true' and True or False,
		'used_licenses': 0,
		'used_voice_licenses': 0,
		'used_siri_licenses': 0,
		'used_anonymous_licenses': 0,
		'role': role,
		'created_at': created_at,
		'created_by': current_user.id,
	}

	manager_id = mongo.db.managers.insert_one(data).inserted_id

	return redirect(url_for('manager.index'))

@page.route('/manager/update/<manager_id>', methods=['POST'])
@login_required
def update(manager_id):
	form = request.form 
	username = form['username'].strip()
	password = form['password'].strip()
	backup = form['backup']
	enable = form['enable']
	role = form.get('role', 'sub-agent')
	voice_licenses = to_int(form['voice_licenses'])
	siri_licenses = to_int(form['siri_licenses'])
	anonymous_licenses = to_int(form['anonymous_licenses'])
	licenses = voice_licenses + siri_licenses + anonymous_licenses

	if current_user.role == 'agent':
		# 获取当前管理员数据
		manager = mongo.db.managers.find_one({'username': current_user.id})
		manager_voice_licenses = manager.get('voice_licenses')
		manager_siri_licenses = manager.get('siri_licenses')
		manager_anonymous_licenses = manager.get('anonymous_licenses')
		manager_used_voice_licenses = manager.get('used_voice_licenses')
		manager_used_siri_licenses = manager.get('used_siri_licenses')
		manager_used_anonymous_licenses = manager.get('used_anonymous_licenses')

		if voice_licenses + manager_used_voice_licenses > manager_voice_licenses:
			flash('语音授权超出可用值！')
			return redirect(url_for('manager.index'))
		if siri_licenses + manager_used_siri_licenses > manager_siri_licenses:
			flash('siri授权超出可用值！')
			return redirect(url_for('manager.index'))
		if anonymous_licenses + manager_used_anonymous_licenses > manager_anonymous_licenses:
			flash('匿名授权超出可用值！')
			return redirect(url_for('manager.index'))
		# 增量
		inc = {
			'used_licenses': voice_licenses + siri_licenses + anonymous_licenses, 
			'used_voice_licenses': voice_licenses, 
			'used_siri_licenses': siri_licenses,
			'used_anonymous_licenses': anonymous_licenses,
		}
		mongo.db.managers.update({'username': current_user.id}, {'$inc': inc})

	manager = {
		'username': username,
		'password': password,
		'backup': backup,
		'role': role,
		'anonymous_licenses': anonymous_licenses,
		'voice_licenses': voice_licenses,
		'siri_licenses': siri_licenses,
		'licenses': licenses,
		'enable': enable == 'true' and True or False,
	}

	result = mongo.db.managers.update_one({'_id': ObjectId(manager_id)}, {'$set': manager})

	return redirect(url_for('manager.index'))

@page.route('/manager/edit/<manager_id>', methods=['GET'])
@login_required
def edit(manager_id):
	manager = mongo.db.managers.find_one({'_id': ObjectId(manager_id)})
	return render_template('managers/edit.html', manager=manager)

@page.route('/manager/show/<manager_id>', methods=['GET'])
@login_required
def show(manager_id):
	manager = mongo.db.managers.find_one({'_id': ObjectId(manager_id)})
	users = mongo.db.users.find({'created_by': manager.get('username')})
	return render_template('managers/show.html', manager=manager, users=users)

@page.route('/manager/disable/<manager_id>', methods=['GET'])
def disable(manager_id):
	result = mongo.db.managers.update_one({'_id': ObjectId(manager_id)}, {'$set': {'enable': False}})
	return redirect(url_for('manager.index'))

@page.route('/manager/delete/<manager_id>', methods=['GET'])
def delete(manager_id):
	mongo.db.managers.remove({'_id': ObjectId(manager_id)})
	return redirect(url_for('manager.index'))

bdp/views/user.py
# encoding: utf-8

from datetime import datetime
from bson.objectid import ObjectId
from functools import wraps

from flask import Blueprint
from flask import render_template
from flask import abort
from flask import request
from flask import Response
from flask import flash
from flask import redirect
from flask import url_for
from flask import json
from flask import jsonify
from flask import current_app as app
from flask_paginate import Pagination

from flask.ext.login import current_user
from flask.ext.login import login_required

from pymongo.errors import DuplicateKeyError

from bdp import mongo

def to_int(num, default=1):
	""" 转化为整形 """
	try:
		return int(num)
	except Exception, e:
		return default

def check_auth(username, password):
	""" 校验用户名和密码是否正确 """
	return username == 'admin' and password == 'secret'

def authenticate():
	""" Sends a 401 response that enables basic auth """
	return Response(
	'Could not verify your access level for that URL.\n'
	'You have to login with proper credentials', 401,
	{'WWW-Authenticate': 'Basic realm="Login Required"'})

def requires_auth(f):
	@wraps(f)
	def decorated(*args, **kwargs):
		auth = request.authorization
		if not auth or not check_auth(auth.username, auth.password):
			return authenticate()
		return f(*args, **kwargs)
	return decorated

page = Blueprint('user', __name__, template_folder='templates')

@page.route('/')
@login_required
def index():
	limit = 100
	page = to_int(request.args.get('page'))
	_type = request.args.get('_type')

	if current_user.role != 'root':
		created_by = current_user.id
		q = {'created_by': created_by}
		current_mananger = mongo.db.managers.find_one({'username': current_user.id})
		hint = '已使用语音授权：%s/%s，已使用siri授权：%s/%s，已使用匿名授权：%s/%s' % \
		(current_mananger['used_voice_licenses'], current_mananger['voice_licenses'],
			current_mananger['used_siri_licenses'], current_mananger['siri_licenses'],
			current_mananger.get('used_anonymous_licenses', 0), current_mananger.get('anonymous_licenses',0),)
	else:
		q = {}
		hint = ''
		created_by = None

	if _type:
		q['type'] = _type

	users = mongo.db.users.find(q).sort([('created_at', -1)]).skip(limit*(page-1)).limit(limit)
	total = mongo.db.users.count(q)
	pagination = Pagination(page=page, per_page=limit, total=total, record_name='users')
	return render_template('users/index.html', users=users, pagination=pagination, _type=_type, hint=hint)

@page.route('/user/new', methods=['GET'])
@login_required
def new():
	user = {}
	return render_template('users/new.html', user=user)

@page.route('/api/users', methods=['POST'])
def multiple_create():
	try:
		data = request.get_json()
		users = data.get('users')
		formatted_users = []
		for user in users:
			if user.get('type', '') == 'siri':
				user['udid'] += '-W'
			elif user.get('type', '') == 'anonymous':
				user['udid'] += '-V'
			user['status'] = True
			user['created_at'] = datetime.now()
			user['created_by'] = None
			formatted_users.append(user)
		mongo.db.users.insert(formatted_users)
		return jsonify({'code': 200})
	except Exception, e:
		return jsonify({'code': 500})

	

@page.route('/users', methods=['POST'])
@login_required
def create():
	try:
		form = request.form
		username = form['username'].strip()
		backup = form['backup']
		status = form['status']
		_type = form['type']
		udid = form['udid'].strip()
		created_at = datetime.now()

		if current_user.role != 'root':
			created_by = current_user.id
		else:
			created_by = None

		manager = mongo.db.managers.find_one({'username': current_user.id})

		if manager.get('enable') == False:
			# 管理被禁用
			flash('无操作权限')
			return redirect(url_for('user.index'))

		inc = {'used_licenses': 1}

		if _type == 'siri':
			udid = '%s-W' % udid
			if manager.get('role') != 'root':
				siri_licenses = manager.get('siri_licenses')
				used_siri_licenses = manager.get('used_siri_licenses')
				if siri_licenses <= used_siri_licenses:
					flash('siri授权数不足')
					return redirect(url_for('user.index'))
				inc['used_siri_licenses'] = 1
		elif _type == 'anonymous':
			udid = '%s-V' % udid
			if manager.get('role') != 'root':
				anonymous_licenses = manager.get('anonymous_licenses')
				used_anonymous_licenses = manager.get('used_anonymous_licenses')
				if anonymous_licenses <= used_anonymous_licenses:
					flash('匿名授权数不足')
					return redirect(url_for('user.index'))
				inc['used_anonymous_licenses'] = 1
		else:
			if manager.get('role') != 'root':
				voice_licenses = manager.get('voice_licenses')
				used_voice_licenses = manager.get('used_voice_licenses')
				if voice_licenses <= used_voice_licenses:
					flash('语音授权数不足')
					return redirect(url_for('user.index'))
				inc['used_voice_licenses'] = 1


		user = {
			'type': _type,
			'username': username,
			'backup': backup,
			'udid': udid,
			'status': status == 'true' and True or False,
			'created_at': created_at,
			'created_by': created_by,
		}

		user_id = mongo.db.users.insert_one(user).inserted_id

		mongo.db.managers.update({'username': current_user.id}, {'$inc': inc})
		return redirect(url_for('user.index'))
	except DuplicateKeyError:
		flash('udid重复')
		return redirect(url_for('user.index'))
	except Exception, e:
		flash(e)
		return redirect(url_for('user.index'))
		
@page.route('/user/update/<user_id>', methods=['POST'])
@login_required
def update(user_id):
	try:
		form = request.form 
		_type = form['type']
		username = form['username'].strip()
		backup = form['backup']
		status = form['status']
		udid = form['udid'].strip()

		if _type == 'siri':
			udid = '%s-W' % udid
		elif _type == 'anonymous':
			udid = '%s-V' % udid

		user = {
			'type': _type,
			'username': username,
			'udid': udid,
			'status': status == 'true' and True or False,
			'backup': backup,
		}

		result = mongo.db.users.update_one({'_id': ObjectId(user_id)}, {'$set': user})
	except DuplicateKeyError:
		flash('udid重复')
	except Exception, e:
		flash(e)
	finally:
		return redirect(url_for('user.index'))

@page.route('/user/edit/<user_id>', methods=['GET'])
@login_required
def edit(user_id):
	user = mongo.db.users.find_one({'_id': ObjectId(user_id)})
	return render_template('users/edit.html', user=user)

@page.route('/user/delete/<user_id>', methods=['GET'])
@login_required
def delete(user_id):
	mongo.db.users.remove({'_id': ObjectId(user_id)})
	return redirect(url_for('user.index'))

@page.route('/user/statistics', methods=['GET'])
def statistics():
	"""统计"""
	total = mongo.db.users.count()

	condition = [
     	{ '$project': {'day': {'$dateToString': { 'format': "%Y-%m-%d", 'date': "$created_at" }}}},
     	{ '$group': {'_id': "$day", 'number': {'$sum': 1 }}},
     	{ '$sort': {'_id': -1}},
   	]

	result = mongo.db.users.aggregate(condition)

	return render_template('users/statistics.html', total=total, result=result) 

	

bdp/templates/layout.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
		<meta name="description" content="">
		<meta name="author" content="">
		<title>{% block title %}bdp{% endblock %}</title>
		
		<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/font-awesome.min.css') }}">
		<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/layout.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/pagination.css') }}">
        {% block css %}{% endblock %}
        
	</head>
	<body>
		<nav class="navbar navbar-inverse navbar-fixed-top">
			<div class="container-fluid">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="#">管理平台</a>
				</div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{{ url_for('user.index')}}">用户列表</a></li>
                        
                        
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ current_user.id }} <span class="caret"></span></a>
    
                            <ul class="dropdown-menu">
                            {% if current_user.role in ['root', 'agent'] %}
                                <li><a href="{{ url_for('manager.index') }}">代理管理</a></li>
                            {% endif %}
                            {% if current_user.role == 'root' %} 
                                <li><a href="{{ url_for('user.statistics') }}">用户统计</a></li>
                            {% endif %}
                                <li><a href="{{ url_for('manager.logout') }}">退出</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container-fluid">
            <div class="row">
                <div class="main">
                    <div id="body">
                         {% with messages = get_flashed_messages() %}
                            {% if messages %}
                                <div class="alert alert-danger" role="alert">
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                    <ul class="flashes">
                                        {% for message in messages %}
                                            <li>{{ message }}</li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            {% endif %}
                        {% endwith %}
                        {% block body %} {% endblock %}
                    </div>
                </div>
            </div>
        </div>
    	<script type="text/javascript" src="{{ url_for('static', filename='js/jquery-1.11.3.min.js') }}"></script>
    	<script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
        {% block js %}{% endblock %}
    </body>
</html>

bdp/templates/login.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>登录页</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/login.css') }}">
</head>
<body>
    <div class="container">
        <form class="form-signin" method="POST" action="login">
            <!-- <h2 class="form-signin-heading">登录</h2> -->
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    <div class="alert alert-danger" role="alert">
                        <ul class="flashes">
                            {% for message in messages %}
                                <li>{{ message }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
            {% endwith %}
            <label for="input-username" class="sr-only">Email address</label>
            <input type="text" id="input-username" class="form-control" placeholder="Email address" name="username" required autofocus>
            <label for="input-password" class="sr-only">Password</label>
            <input type="password" id="input-password" class="form-control" placeholder="Password" name="password" required>
            <div class="checkbox">
                <label>
                    <input type="checkbox" value="remember-me"> Remember me
                </label>
            </div>
            <button class="btn btn-lg btn-primary btn-block" type="submit">登录</button>
        </form>
    </div>
</body>
</html>